#!/bin/sh
# Based on Lukesmith's famous "get a menu of emojis to copy" script.

# This will feed dmenu with ~/.local/share/unicode, a UTF-8 file which contains all sort of unicode characters in the following format
# glyph1 description 1
# glyph2 description 2
# ...
# Using dmenu fuzzy find, you can quickly get the character you are looking for and pressing enter copies it in the clipboard.


# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/.local/share/unicode | dmenu -fn 'Mononoki Nerd Font:size=15'  -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	printf "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
