#!/bin/sh
sortie=$(pactl list short sinks | grep RUNNING | cut -c 1-1)
dacmagic="0"
hp="2"

if [ $sortie == $hp ];  then
  pacmd set-default-sink 0
elif [ $sortie == $dacmagic ]; then
  pacmd set-default-sink 2
fi

